### ISSUE TITLE
robots: `User-agent: *` might appear twice in robots.txt

### ISSUE THREAD

**Issue by davidsneighbour** [davidsneighbour/hugo-modules#104]
Given that users could configure for instance:

```toml
[[dnb.robots.useragents]]
name = "*"
disallow = ["/cdn-cgi/"]
```

This will lead to two separate `User-agent: *` sections. One when the local configuration is parsed and one when the global disallow via frontmatter is ranged. 

Fix: check in the first range for `name` and if it's `*` move the items to the global range.
